### PR TITLE
Reworked UI

### PR DESCRIPTION
**Pull request by Epicguru**
Hi!
I've reworked the UI for the loading screen.
The current loading screen is very functional, but also quite ugly (no offence, I can tell that loads of effort went into the rest of the code), so I reworked it to be more appealing.
Functionality has not been changed (apart from 1 small technical change, and 1 bug fix, see below).

**Changes:**

- Fixed bug where progress bar would go negative (the calculated percentage was less than zero).
- Swapped order of 'stage' and 'step' progress bars. To me it makes more sense for the 'global progress' bar to be on top.
- Made 'step' progress bar smaller and thinner, to emphasize main loading bar.
- Global progress bar percentage now takes into account stage loading percentage. So for example, instead of the percentage being calculated as (4/11) it would be calculated as (4.25/11). This makes the bar progress more smoothly.
- Both progress bars interpolate to the target percentage value. Purely visual change that just makes it look smoother.
- Changed the text(s) and colors for both progress bars.
- Instead of solid background color, the default Rimworld background is shown, in a darker version.
- **Technical change:** In _BetterLoadingMain.cs_, changed _Resources.FindObjectsOfTypeAll_ to _Object.FindObjectOfType_. Resources.FindObjectsOfType will return assets that have not been instantiated. In this case, it doesn't make much of a difference, but it's still better practice to use Object.FindObjectOfType to find an instantiated asset.

I also tried to stick to your programming style and .NET 4.8's conventions, but if you want me to make any changes in that regard just let me know.

P.S. I really like how professional and clean all of the code is, using _nameof()_ and that kind of stuff :)

### CODE REVIEW

**Comment by SamboyCoding** [comment]
Oh my god, this looks amazing! I'll do some testing and make sure this doesn't break anything, but this is phenomenal work. Thank you so much!

And yeah, I have little artistic talent so I went for function over form.

**Comment by Epicguru** [comment]
I did experience loading occasionally stopping, usually when loading HugsLib. Happened maybe 10% of times I ran the game.

Might be unrelated to this mod, or caused by another mod.
I sometimes experience crashing when developing my own mods so it may be caused by me attaching a debugger to the rimworld process, idk.

**Comment by Epicguru** [comment]
Any updates on this PR? Sorry to bother you if you don't have the time.

**Comment by SamboyCoding** [comment]
Oh man time flies. Yeah I've been busy, sorry about that. I can't make any promises but I'll try to get this in asap.

**Comment by SamboyCoding** [comment]
Alright, looks good, merging!

**Pull request merged**
